config/routes.rb
Cmsify::Engine.routes.draw do
  scope :cmsify do
    concern :sortable do
      put :sort, on: :collection
    end
    resources :assets
    resources :paginate_assets, :only => [:index]

    scope '/content' do
      Cmsify.config.content_types.each do |n|
        namespace n, path: n.to_s.tableize do
          resources :items, concerns: :sortable
          resources :collections, concerns: :sortable do
            resources :children, controller: :collections
            resources :items
          end
        end
      end
    end

    Cmsify.config.cmsified_resources.each do |n|
      resources n
    end
    resources :urls
    resources :pages do
      resources :children, controller: :pages
    end

    resources :collects, only: [:destroy], concerns: :sortable
    ['content'].each do |p|
      get p, :controller => 'home', :action => p
    end
    root to: 'home#content'
  end

  get '*path', to: 'page_renders#show'
  
end

app/controllers/cmsify/application_controller.rb
class Cmsify::ApplicationController < ActionController::Base
end

app/controllers/cmsify/assets_controller.rb
class Cmsify::AssetsController < Cmsify::BaseController
  # load_and_authorize_resource
  respond_to :json, :html

  before_action :build_asset, only: :new
  before_action :load_asset, only: [:show, :destroy]

  def index
    @assets = ::Cmsify::Asset.all.filter_by_scope(params.slice(:searched_term))
    @assets = @assets.page(params[:page]).per(30) if request.format == :html
    @assets = @assets.images if request.format == :json
    respond_with(@assets, each_serializer: ::Cmsify::Tinymce::AssetSerializer, adapter: :attributes)
  end

  def create
    @asset = ::Cmsify::Asset.new(asset_params)
    if @asset.save!
      render json: { asset: Cmsify::AssetSerializer.new(@asset) }
    else
      render json: { error: 'Failed to process' }, status: 422
    end
  end

  def destroy
    @asset.destroy
    respond_with(@asset)
  end

  def asset_params
    # TODO: Make these params more conventional. It will probably require changing `cmsify_assets`
    { attachment: params.require(:file) }
  end

  private
    def build_asset
      @asset = ::Cmsify::Asset.new
    end

    def load_asset
      @asset = ::Cmsify::Asset.find(params[:id])
    end

# if we decide to have check boxes where you can delete multiple assets at once, whcih we should
# def delete_assets
#   Asset.where(id: params[:asset_contents]).destroy_all
#   redirect_to [ :root]
# end

end

app/controllers/cmsify/authenticated_controller.rb
class Cmsify::AuthenticatedController < Cmsify::ApplicationController
end

app/controllers/cmsify/base_controller.rb
class Cmsify::BaseController < Cmsify::AuthenticatedController
  layout 'cmsify/base'
  responders :flash, :http_cache
  respond_to :html
  protect_from_forgery with: :exception
  def current_ability
    defined?(super) ? super : nil
  end

  before_action :store_front_end_location

  def store_front_end_location
    return unless request.try(:referrer).present?
    parsed_referrer = URI.parse(request.referrer)
    referrer_root_path = parsed_referrer.path.split('/')[1]
    current_root_path = request.original_fullpath.split('/')[1]

    return unless request.host == parsed_referrer.host
    return unless referrer_root_path != current_root_path

    session[:cmsify_return_url] = request.referrer
  end
  private
    def load_content
      @content_types = Cmsify.config.content_types.sort
      if ActiveRecord::Base.connection.data_source_exists? ::Cmsify::Collection.table_name
        @collection_groups = ::Cmsify::Collection.accessible_by(current_ability).order(name: :asc).without_parent
          .includes(:items, children: [:items, children: [:items, children: [:items, children: :items]]])
          .group_by {|collection| collection.type.deconstantize.demodulize.underscore.to_sym }
      else
        flash[:error] = "You need to run the cmsify database migrations: `rails cmsify:install:migrations` and `rake db:migrate`"
      end
    end
end

app/controllers/cmsify/cmsifieds_controller.rb
class Cmsify::CmsifiedsController < Cmsify::BaseController
  include ::Cmsify::DynamicallyControllable

  def create
    @resource.save
    respond_with(@resource, location: [cmsify, controller_class_collection_symbol])
  end

  def update
    @resource.update(resource_params)
    respond_with(cmsify, :edit, @resource)
  end

  def destroy
    @resource.destroy
    respond_with(cmsify, @resource)
  end
end

app/controllers/cmsify/collects_controller.rb
class Cmsify::CollectsController < Cmsify::BaseController
  before_action :load_collect

  def destroy
    @collect.destroy
    respond_with @collect, location: [:edit, @collect.collection]
  end

  private
    def load_collect
      @collect = ::Cmsify::Collect.accessible_by(current_ability).find(params[:id])
    end
end

app/controllers/cmsify/home_controller.rb
class Cmsify::HomeController < Cmsify::BaseController
  before_action :load_content

end

app/controllers/cmsify/paginate_assets_controller.rb
class Cmsify::PaginateAssetsController <  Cmsify::BaseController
  
  def index
    @assets = ::Cmsify::Asset.page(params[:page]).per(30)
  end
  
end

app/helpers/cmsify/base_helper.rb
module Cmsify
  module BaseHelper
    def cmsify_header(heading)
      cmsify_section do
        concat(render partial: "cmsify/partials/breadcrumbs" )
        concat(content_tag(:h2, heading))
      end
    end

    def cmsify_section(&block)
      content_tag :section, class: "full-width" do
        content_tag :article do
          content_tag :div, class: "uk-width-1-1" do
            yield
          end
        end
      end
    end

    def cmsify_card(class_name = '', &block)
      content_tag :div, class: "card #{ class_name }" do
        yield
      end
    end

    def primary_button(label, path, html_class)
      link_to label, path, class: "button#{ " " + html_class if html_class.present? }"
    end

    def secondary_button(label, path, html_class)
      primary_button label, path, "secondary#{ " " + html_class if html_class.present? }"
    end

    def back_button
      secondary_button "Cancel", :back, "uk-margin-small-right"
    end

    def cmsify_form_for(path, options = {}, &block)
      options = options.deep_merge(html: { class: 'js-changed-form-modal' }) unless options[:track_changes] == false
      simple_form_for(path, options, &block)
    end

    def cmsify_field f, field_name, schema_options={}
      # TODO: We need to be able to pass all input options, placeholder, class, input_html, not just label
      input_options = { label: schema_options[:label] }
      content_tag :div, class: "row #{"uk-invisible uk-animation-fade" if [:text, :datetime].include?(schema_options[:type])}" do
        case schema_options[:type]
          when :year
            input_options = input_options.deep_merge(as: :date, discard_month: true,
              discard_day: true, start_year: Date.today.year - 50, end_year: Date.today.year)
            f.input field_name, input_options
          when :string
            f.input field_name, input_options
          when :text
            concat(f.input field_name, input_options.deep_merge(input_html: { class: 'tinymce' }))
            if schema_options[:hint].present?
              concat(content_tag(:div, class: "uk-text-muted") { schema_options[:hint] })
            end
          when :datetime
            input_options = input_options.deep_merge(as: :string, input_html: { class: "js-flatpickr" }, placeholder: input_options[:label])
            f.input field_name, input_options
        end
      end
    end

    def delete_button(resource)
      link_to [cmsify, resource], method: :delete, data: { confirm: 'Are you sure?' }, class: "uk-flex uk-flex-middle" do
        concat(content_tag(:i, '', "uk-icon": "icon: trash"))
        concat(content_tag(:div, "Delete", class: "uk-margin-small-left"))
      end
    end

    def submit_section(f)
      cmsify_section do
        content_tag :div, class: "uk-flex uk-flex-right" do
          concat(area :submit)
          concat(f.submit 'Save', class: 'button primary')
        end
      end
    end

    def status_for_resource(resource)
      content_tag :span, class: "tip #{ resource.active? ? 'uk-text-success' : 'uk-text-warning' }",
        data: { hover: resource.state.capitalize } do
          "&#9679;".html_safe
      end
    end

    def descendents_accordion resource, current_node, index = 0
      content_tag(:li, class: "#{"uk-parent" if current_node.children.size > 0} #{"uk-open" if resource && resource.has_ancestor?(current_node)}") do
        concat(
          content_tag(:div, class: "uk-flex uk-flex-middle blm-uk-nav-row", style: "padding-left: #{ (index + 1) * 15 }px") do
            concat(content_tag(:div, "", class: "uk-flex-none blm-uk-nav-spacer #{"blm-uk-nav-toggle" if current_node.children.size > 0}"))
            concat(active_link_to(current_node.name, [cmsify, :edit, current_node], class: "uk-flex-1"))
            concat(
              content_tag(:div, class: "uk-flex uk-flex-middle uk-flex-none uk-margin-small-left") do
                if resource == current_node
                  if current_node.children.size > 1
                    concat( link_to("", "#", "uk-toggle": "target: #manage-child-collections", class: "button transparent secondary icon-move-vertical"))
                  end
                  concat(link_to("", "#", "uk-toggle": "target: #offcanvas-collection", class: "button transparent secondary icon-edit"))
                  concat( link_to("", [cmsify, :new,  current_node, :child], class: "button transparent secondary icon-addcircle"))
                end
              end
            )
          end
        )
        concat(
          content_tag(:ul, class: "uk-nav-default uk-nav-parent-icon", "uk-nav": "toggle: > div > .blm-uk-nav-toggle; multiple: true;") do
            current_node.children.each do |child|
              concat(descendents_accordion(resource, child, index + 1))
            end
          end
        )
      end
    end
  end
end

app/helpers/cmsify/public_helper.rb
module Cmsify
  module PublicHelper
    def cmsify_flash
      [:notice, :alert, :error].each do |flash_type|
        if flash[flash_type]
          concat(
            content_tag(:div, class: "alert #{ flash_type }", data: { uk_alert: "{}" }) do
              concat('<a class="uk-alert-close close"></a>'.html_safe)
              concat(
                content_tag(:dl) do
                  concat(content_tag :dt, flash_type.to_s.titleize)
                  concat(content_tag :dd, flash[flash_type])
                end
              )
            end
          )
        end
      end
    end

    def cmsify_url_title default_title
      current_url.try(:title) || default_title
    end

    def cmsify_url_description default_description
      current_url.try(:description) || default_description
    end

    def cmsify_admin?
      is_admin?
    end

    def cmsify_tools
      if is_admin?
        cmsify_tool({
          class_name: "cmsify-adminified__toolbar",
          icon_class: "window-maximize",
          href: current_url ? url_for([cmsify, :edit, current_url]) : url_for([cmsify, :new, :url, url: request.path]),
          label: ""
        })
      end
    end

    def cmsify_content_for(collection_name_or_object, options = {}, &block)
      with_cmsify_log_level do
        options = process_options(options)
        collection = Collection.new_find_or_create_by_object_permaname(collection_name_or_object)
        collection.update({ configuration_type: options[:configuration] }) unless collection.send("#{ options[:configuration] }?")
        template_builder = Cmsify::TemplateBuilder.new(collection, app_current_user, current_ability, is_admin?, &block)
        content_items = Cmsify::TemplateBuilder.get_content_items_for_collection(collection, app_current_user, current_ability, is_admin?, options[:params])
        output = ""
        output = capture_yield(template_builder, &block)
        wrapped_output = wrap_output(output, options[:container_html])
        sanitized_output = cmsify_sanitize(wrapped_output)
        adminify sanitized_output, collection, content_items, options, !block_given?
      end
    end

    # TODO: This method needs a lot of cleanup and abstraction
    def cmsify_content object_name, options = {}, &block
      with_cmsify_log_level do
        options = process_options(options)
        collection = get_configured_collection(object_name, options[:configuration])
        output = ""
        # TODO: Move access logic to ability
        if (collection.state == "active" || is_admin?)
          content_items = Cmsify::TemplateBuilder.get_content_items_for_collection(collection, app_current_user, current_ability, is_admin?, options[:params])

          if content_items.any?
            output = content_items.map do |item|
              if block_given? && block.parameters.any?
                item.configuration = collection.configuration_type
                capture_yield(item, &block)
              else
                options[:content_method].to_s.split('.').inject(item, :try)
              end
            end.join("")
          end

          output = output_or_default(output, options[:default], &block)
          wrapped_output = wrap_output(output, options[:container_html])
          sanitized_output = cmsify_sanitize(wrapped_output)
          adminify sanitized_output, collection, content_items, options, !block_given?
        end
      end
    end

    private
      def cmsify_tool(class_name: nil, icon_class:, href:, label:)
        link_to href, data: { turbolinks: false }, class: "cmsify-adminified__content-bar #{class_name || "uk-position-top-right"}" do
          if label.present?
            concat(content_tag(:span, label, class: "uk-margin-small-right"))
          end
          concat( fa_icon(icon_class))
        end
      end

      def current_url
        @current_url ||= Cmsify::TemplateBuilder.accessible_results(Url.all, current_ability, is_admin?).find_by_url(request.path)
      end

      def app_current_user
        defined?(current_user) ? current_user : nil
      end

      def process_options(options)
        if options.is_a?(String)
          options = { default: options }
        end
        options[:configuration] ||= :default
        options[:content_method] ||= "body"
        return options
      end

      def get_configured_collection(name, configuration)
        collection = Collection.find_or_create_by_object_name(name)
        collection.update({ configuration_type: configuration }) unless collection.send("#{ configuration }?")
        return collection
      end

      def output_or_default(output, default_content, &block)
        if output.blank?
          output = case default_content.class.name.demodulize.underscore.to_sym
            when :safe_buffer, :string
              default_content
            when :proc
              capture { default_content.call }
            else
              capture_yield(RecursiveOpenStruct.new(default_content), &block)
            end
        end
        return output
      end

      def wrap_output(output, container_html)
        if container_html.present?
          output = capture do
            content_tag :div, container_html do
              output
            end
          end
        end
        return output
      end

      def with_cmsify_log_level &block
        Rails.logger.silence("Logger::#{ ENV['CMSIFY_LOG_LEVEL'] || 'INFO' }".constantize) { yield }
      end

      def is_admin?
        @is_admin ||= defined?(current_admin) && (current_admin.class.name.downcase.include?("admin") || current_admin.try(:admin?)) && admin_signed_in?
      end

      def adminify(content, collection, content_items, options, is_inline)
        if !is_admin?
          if options[:container]
            content_tag (options[:container].try(:[], :tag) || :div), class: options[:container].try(:[], :class), data: options[:container].try(:[], :data) do
              content
            end
          else
            content
          end
        else
          toolbar = capture do
            cmsify_tool({
              icon_class: "pencil",
              href: edit_url(collection),
              class_name: options[:container].try(:[], :content_bar_class_name),
              label: options[:container].try(:[], :label)
            })
          end
          content_tag((options[:container].try(:[], :tag) || :div), data: options[:container].try(:[], :data), class: "cmsify-adminified #{ 'cmsify-adminified--inline' if is_inline } #{ options[:container].try(:[], :class) }".squish) do
            toolbar + content
          end
        end
      end

      def edit_url(collection)
        components = case collection.items.size
        when 0
          [:new, collection, :item]
        when 1
          [:edit, collection, :item, id: collection.items.first.id]
        else
          [:edit, collection]
        end
        url_for([cmsify] + components)
      end

      def cmsify_sanitize(content)
        scrubber = Loofah::Scrubber.new do |node|
          node.remove if node.name == 'script'
        end

        sanitize(content, scrubber: scrubber)
      end

      def capture_yield(object, &block)
        capture { yield object } if block_given?
      rescue NoMethodError => e
        logger.error e.inspect
        logger.error e.backtrace.join("\n")
        return unless is_admin?

        if object.try(:valid?) == false && object.errors.any?
          error_message = object.errors.full_messages.to_sentence
        else
          error_message = e.message
        end

        output = capture do
          concat(content_tag :p, "Errors on #{ object.try(:name) }: ", class: "cmsify-error")
          concat(content_tag :span, error_message, class: "cmsify-error")
        end

        return output
      end
  end
end

app/views/cmsify/collections/_collect_row.html.erb
<tr>
  <td>
    <% if f.object.persisted? %>
      <button class="icon-drag-handle drag transparent" type="button"></button>
    <% end %>
    <%= f.hidden_field :rank, class: "js-rank" %>
    <%= f.hidden_field :id %>
    <%= f.hidden_field :collectible_id %>
  </td>
  <td><%= link_to f.object.collectible.try(:name), (f.object.collectible.present? ? [cmsify, :edit,  @collection, :item, id: f.object.collectible.try(:id)] : '') %></td>
  <% if @collection.apply_access_rules? %>
    <td><%= f.object.collectible.cmsify_access_tags.to_sentence if f.object.collectible.present? %></td>
  <% end %>
  <td class="uk-text-center">
    <%= status_for_resource f.object.collectible if f.object.persisted? %>
  </td>
  <td class="uk-text-right">
    <% if f.object.persisted? %>
      <button class="transparent secondary icon-gear js-webui-popover"></button>
      <div class="webui-popover-content">
        <%= collect_remove_button(f.object) %>
      </div>
    <% end %>
  </td>
</tr>

app/views/cmsify/collections/_collection.html.erb
<% index = 0 unless index %>
<tr>
  <td>
    <div style="padding-left: <%= "#{ index * 20 }px" %>">
      <%= link_to collection.name, [cmsify, :edit, collection] %>
    </div>
  </td>
  <td class="uk-text-center cmsify-width-small">
    <%= status_for_resource collection %>
  </td>
</tr>
<% if collection.collections.any? %>
    <%= render partial: "cmsify/collections/collection", collection: collection.collections, locals: { index: index + 1 } %>
<% end %>

app/views/cmsify/collections/_collection_collections_table.html.erb
<table class="cmsify-table cmsify-table--static">
  <thead>
    <tr>
      <th class="uk-text-center cmsify-width-small">Reorder</th>
      <th>Item</th>
      <th class="uk-text-center cmsify-width-small">Status</th>
      <th class="uk-text-right cmsify-width-small">Actions</th>
    </tr>
  </thead>
  <tbody class="js-sortable">
  <% if collections.empty? %>
      <tr class="uk-block-empty">
        <td colspan="5"><p class="uk-text-muted uk-text-center">No collections have been created yet.</p></td>
      </tr>
  <% else %>
    <%= f.simple_fields_for :collections do |collection_fields| %>
      <tr>
        <td class="uk-text-center">
          <button class="icon-drag-handle drag transparent" type="button"></button>
          <%= collection_fields.hidden_field :rank, class: "js-rank" %>
        </td>
        <td><%= link_to collection_fields.object.name, [cmsify, :edit,  collection_fields.object] %></td>
        <td class="uk-text-center">
          <%= status_for_resource collection_fields.object %>
        </td>
        <td class="uk-text-right">
          <button class="transparent secondary icon-gear js-webui-popover"></button>
          <div class="webui-popover-content">
            <%= delete_button(collection_fields.object) %>
            <%= state_toggle_button(collection_fields.object) %>
          </div>
        </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/cmsify/collections/_collections_table.html.erb
<table class="cmsify-table--static">
  <thead>
    <tr>
      <th>Collection</th>
      <th class="cmsify-width-small">Status</th>
    </tr>
  </thead>
  <tbody <%= "class='js-sortable' data-sort-action='#{sort_path}'" if defined?(sort_path) %>>
  <% if collections.empty? %>
      <tr class="uk-block-empty">
        <td colspan="5"><p class="uk-text-muted uk-text-center">No collections have been created yet.</p></td>
      </tr>
  <% else %>
    <%= render(partial: "cmsify/collections/collection", collection: collections) %>
  <% end %>
  </tbody>
</table>

app/views/cmsify/collections/_form.html.erb
<!-- TODO: This form should be a template instead of a partial. @collection.persisted? is used too many times -->
<% add_collection_breadcrumbs(@collection) %>
<%= render layout: "cmsify/partials/collection_tree" do %>
  <%= cmsify_form_for(@collection, url: action) do |f| %>
    <% replace :header_utility do %>
      <%= f.submit 'Save', class: 'button primary', form: f.options[:html][:id] %>
    <% end %>
    <%= render partial: "cmsify/partials/invalid", locals: { invalid: @collection } %>
    <%= cmsify_header("New collection") unless @collection.persisted? %>
    <section>
      <article class="uk-flex-column">
        <div class="has-sections card">
          <% if @collection.persisted? %>
            <div class="card-section">
              <div class="uk-flex uk-flex-between uk-flex-top">
                <h3 class="uk-margin-remove"><%= f.object.name %></h3>
                <div class="uk-flex uk-flex-middle">
                  <button class="button secondary uk-margin-small-right js-select-existing uk-margin-bottom" type="button"
                    data-target="#add-items" data-list="#collects"
                    data-item-template="<%= html_escape_once(f.simple_fields_for(:collect, ::Cmsify::Collect.new) { |collect| render "collect_row", f: collect }) %>">Add existing items</button>
                  <%= secondary_button("Create new item", [cmsify, :new,  @collection, :item], 'js-check-changed uk-margin-bottom uk-margin-small-right') %>
                </div>
              </div>
              <table class="sf-table cmsify-table--static">
                <thead>
                  <tr>
                    <th class="cmsify-width-small">Reorder</th>
                    <th>Item</th>
                    <% if @collection.apply_access_rules? && has_access_tags? %>
                      <th>Access Tags</th>
                    <% end %>
                    <th class="uk-text-center cmsify-width-small">Status</th>
                    <th class="uk-text-right cmsify-width-small">Actions</th>
                  </tr>
                </thead>
                <tbody class="js-sortable" id="collects">
                <% if @collection.collects.empty? %>
                    <tr class="uk-block-empty">
                      <td colspan="5"><p class="uk-text-muted uk-text-center">No items have been added to this collection</p></td>
                    </tr>
                <% else %>
                  <%= f.simple_fields_for :collects do |collect| %>
                    <%= render "collect_row", f: collect %>
                  <% end %>
                <% end %>
                </tbody>
              </table>
            </div>
            <div id="manage-child-collections" uk-modal="container: false;">
              <div class="uk-modal-dialog uk-margin-auto-vertical">
                <div class="uk-modal-header">
                  <h4 class="uk-margin-remove">Reorder collections</h4>
                  <a class="uk-modal-close uk-close uk-position-top-right uk-margin uk-margin-right" uk-icon="icon: close"></a>
                </div>
                <div class="uk-modal-body uk-panel uk-panel-scrollable">
                  <% if @collection.collections.any? %>
                    <%= render partial: "collection_collections_table", locals: { f: f, collections: @collection.collections} %>
                  <% end %>
                </div>
                <div class="uk-modal-footer uk-text-right">
                  <button class="button secondary uk-margin uk-margin-small-right uk-modal-close">Cancel</button>
                  <%= f.submit 'Save', class: 'button primary' %>
                </div>
              </div>
            </div>
            <div id="add-items" class="js-checkbox-modal uk-text-left" uk-modal="container: false;">
              <div class="uk-modal-dialog uk-margin-auto-vertical">
                <div class="uk-modal-header">
                  <h4 class="uk-margin-remove">Select Items to Add to this Collection</h4>
                  <div class="uk-inline uk-margin-small-bottom uk-margin-small-top">
                      <span class="uk-form-icon" uk-icon="icon: search"></span>
                      <%= search_field_tag :searched_term, nil, placeholder: 'Search items', data: {filter_search: "#item-list"} %>
                  </div>
                  <a class="uk-modal-close uk-close uk-position-top-right uk-margin uk-margin-right" uk-icon="icon: close"></a>
                </div>
                <div class="uk-modal-body uk-panel uk-panel-scrollable">
                  <table class="table--static js-selectable-rows">
                    <thead>
                      <tr>
                        <th>Item</th>
                        <th class="cmsify-width-small">Status</th>
                        <th class="cmsify-width-small">Actions</th>
                      </tr>
                    </thead>
                    <tbody id="item-list">
                      <%= f.collection_check_boxes :item_ids, @items, :id, :name do |b| %>
                        <tr>
                          <td><%=b.object.name %></td>
                          <td class="uk-flex-right">
                            <%= status_for_resource b.object %>
                          </td>
                          <td class="uk-flex-right"><%= b.label {b.check_box} %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
                <div class="uk-modal-footer uk-text-right">
                  <button class="button secondary uk-margin js-cancel-add-items uk-margin-small-right js-modal-cancel">Cancel</button>
                  <button class="button primary js-modal-done" autofocus>Done</button>
                </div>
              </div>
            </div>
            <div uk-offcanvas="container: false; overlay: true;" id="offcanvas-collection">
              <div class="uk-offcanvas-bar">
                <div class="uk-overflow-auto uk-height-1-1 cmsify-offcanvas-overflow-container">
                  <div class="card has-sections">
                    <div class="card-section">
                      <%= f.hidden_field :collection_id %>
                      <h2>Collection Settings</h2>
                      <% if f.object.persisted? %>
                        <%= f.input :name %>
                        <%= f.input :slug, wrapper_html: { class: "uk-margin" } %>
                      <% end %>
                    </div>
                    <hr />
                    <%= render partial: "cmsify/partials/image_upload_card", locals: {f: f, resource_name: 'featured_image', model: :collection} %>
                    <hr />
                    <% if has_access_tags? %>
                      <div class="card-section">
                        <h4>Settings</h4>
                        <%= f.input :apply_access_rules, as: :boolean, label: "Apply access tag rules to items in this collection" %>
                      </div>
                      <hr />
                    <% end %>
                    <div class="card-section">
                      <h4>Status</h4>
                      <%= render partial: "cmsify/partials/publish_state", locals: {f: f} %>
                    </div>

                  </div>
                </div>
                <div class="card-section uk-padding-remove-vertical uk-flex uk-flex-right uk-flex-middle uk-position-bottom cmsify-offcanvas-footer">
                  <hr />
                  <button class="button secondary uk-margin-small-right" type="button" uk-toggle="target: #offcanvas-collection">Cancel</button>
                  <%= f.submit 'Save', class: 'button primary' %>
                </div>
              </div>
            </div>
          <% else %>
            <div class="card-section">
              <%= f.hidden_field :collection_id %>
              <h4>Name</h4>
              <%= f.input :name %>
            </div>
            <hr />
            <%= render partial: "cmsify/partials/image_upload_card", locals: {f: f, resource_name: 'featured_image', model: :collection} %>
            <hr />
            <% if has_access_tags? %>
            <div class="card-section">
              <h4>Settings</h4>
              <%= f.input :apply_access_rules, as: :boolean, label: "Apply access tag rules to items in this collection" %>
            </div>
            <hr />
            <% end %>
            <div class="card-section">
              <h4>Status</h4>
              <%= render partial: "cmsify/partials/publish_state", locals: {f: f} %>
            </div>
            <hr />
          <% end %>
        </div>
      </article>
    </section>
    <% unless f.object.persisted? %>
        <%= submit_section(f) %>
    <% end %>
  <% end %>
<% end %>

app/views/cmsify/collections/edit.html.erb
<%= render layout: 'cmsify/partials/asset_picker' do %>
  <%= render 'form', action: [cmsify, parent_collection_or_namespace, :collection, id: @collection.id] %>
<% end %>

app/views/cmsify/collections/new.html.erb
<% replace :submit do %>
  <%= back_button %>
<% end %>
<% replace :header_back do %>
  <%= back_button %>
<% end %>
<%= render layout: 'cmsify/partials/asset_picker' do %>
  <%= render 'form', action: [cmsify, parent_collection_or_namespace, children_or_collections, id: @collection.id] %>
<% end %>